DROP DATABASE IF EXISTS db_projet06;

CREATE DATABASE db_projet06
    WITH 
    OWNER = rl_projet06
    ENCODING = 'UTF8'
    LC_COLLATE = 'French_France.1252'
    LC_CTYPE = 'French_France.1252'
    TABLESPACE = ts_projet06
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE db_projet06 TO PUBLIC;

GRANT ALL ON DATABASE db_projet06 TO rl_projet06;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO rl_projet06;
