
-- Role
CREATE ROLE rl_projet06 WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';
GRANT postgres TO rl_projet06 WITH ADMIN OPTION;

-- Table Space
DROP TABLESPACE IF EXISTS ts_projet06;

CREATE TABLESPACE ts_projet06  OWNER rl_projet06
  LOCATION 'd:/OpenClassRooms/bd_data';


-- Database

DROP DATABASE IF EXISTS db_projet06;

CREATE DATABASE db_projet06
    WITH
    OWNER = rl_projet06
    ENCODING = 'UTF8'
    LC_COLLATE = 'French_France.1252'
    LC_CTYPE = 'French_France.1252'
    TABLESPACE = ts_projet06
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE db_projet06 TO PUBLIC;

GRANT ALL ON DATABASE db_projet06 TO rl_projet06;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO rl_projet06;
