-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 08:48:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocr_projet06
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocr_projet06` ;

-- -----------------------------------------------------
-- Schema ocr_projet06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocr_projet06` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ocr_projet06` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(256) NULL,
  `email` VARCHAR(256) NULL,
  `mdp` VARCHAR(16) NULL,
  `profil` VARCHAR(2) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topo` ;

CREATE TABLE IF NOT EXISTS `topo` (
  `idtopo` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NULL,
  `nom` VARCHAR(256) NULL,
  `est_publie` INT NULL,
  `est_disponible` INT NULL,
  `resume` VARCHAR(256) NULL,
  `lieu` VARCHAR(45) NULL,
  `date_de_parution` DATE NULL,
  PRIMARY KEY (`idtopo`),
  CONSTRAINT `fk_topo_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_topo_user1_idx` ON `topo` (`user_iduser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spot` ;

CREATE TABLE IF NOT EXISTS `spot` (
  `idspot` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NULL,
  `nom` VARCHAR(45) NULL DEFAULT 'spot_s',
  `localisation` VARCHAR(45) NULL DEFAULT 'localisatiion_spot_s',
  `classification` VARCHAR(45) NULL DEFAULT 'standard',
  PRIMARY KEY (`idspot`),
  CONSTRAINT `fk_spot_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_spot_user1_idx` ON `spot` (`user_iduser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `secteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secteur` ;

CREATE TABLE IF NOT EXISTS `secteur` (
  `idsecteur` INT NOT NULL AUTO_INCREMENT,
  `spot_idspot` INT NULL,
  `nom` VARCHAR(45) NULL DEFAULT 'secteur_s',
  PRIMARY KEY (`idsecteur`),
  CONSTRAINT `fk_secteur_spot1`
    FOREIGN KEY (`spot_idspot`)
    REFERENCES `spot` (`idspot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_secteur_spot1_idx` ON `secteur` (`spot_idspot` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voie` ;

CREATE TABLE IF NOT EXISTS `voie` (
  `idvoie` INT NOT NULL AUTO_INCREMENT,
  `secteur_idsecteur` INT NULL,
  `nom` VARCHAR(45) NULL DEFAULT 'voie_v',
  PRIMARY KEY (`idvoie`),
  CONSTRAINT `fk_voie_secteur1`
    FOREIGN KEY (`secteur_idsecteur`)
    REFERENCES `secteur` (`idsecteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_voie_secteur1_idx` ON `voie` (`secteur_idsecteur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `longueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `longueur` ;

CREATE TABLE IF NOT EXISTS `longueur` (
  `idlongueur` INT NOT NULL AUTO_INCREMENT,
  `voie_idvoie` INT NULL,
  `nom` VARCHAR(45) NULL,
  `cotation` VARCHAR(45) NULL,
  `nombre_de_spits` INT NULL,
  PRIMARY KEY (`idlongueur`),
  CONSTRAINT `fk_longueur_voie1`
    FOREIGN KEY (`voie_idvoie`)
    REFERENCES `voie` (`idvoie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_longueur_voie1_idx` ON `longueur` (`voie_idvoie` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commentaire` ;

CREATE TABLE IF NOT EXISTS `commentaire` (
  `idcommentaire` INT NOT NULL AUTO_INCREMENT,
  `spot_idspot` INT NOT NULL,
  `texte` VARCHAR(256) NULL DEFAULT 'donnes ton avis sur c espot',
  `est_visible` INT NULL DEFAULT 1,
  PRIMARY KEY (`idcommentaire`),
  CONSTRAINT `fk_commentaire_spot`
    FOREIGN KEY (`spot_idspot`)
    REFERENCES `spot` (`idspot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaire_spot_idx` ON `commentaire` (`spot_idspot` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
