-- MySQL Script generated by MySQL Workbench
-- Wed Aug  7 16:36:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocr_projet06
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocr_projet06` ;

-- -----------------------------------------------------
-- Schema ocr_projet06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocr_projet06` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ocr_projet06` ;

-- -----------------------------------------------------
-- Table `ocr_projet06`.`compte_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`compte_utilisateur` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`compte_utilisateur` (
  `id_compte` INT NOT NULL AUTO_INCREMENT,
  `mdp` VARCHAR(45) NOT NULL DEFAULT 'password',
  `login` VARCHAR(64) NOT NULL DEFAULT 'user',
  `droits` CHAR(1) NOT NULL DEFAULT 'R',
  PRIMARY KEY (`id_compte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`utilisateur` (
  `id_utilsateur` INT NOT NULL AUTO_INCREMENT,
  `compte_utilisateur_id_compte` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL DEFAULT '\"ocr.projet06@grimpeur.fr',
  PRIMARY KEY (`id_utilsateur`),
  CONSTRAINT `fk_utilisateur_compte_utilisateur1`
    FOREIGN KEY (`compte_utilisateur_id_compte`)
    REFERENCES `ocr_projet06`.`compte_utilisateur` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_compte_utilisateur1_idx` ON `ocr_projet06`.`utilisateur` (`compte_utilisateur_id_compte` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`topo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`topo` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`topo` (
  `id_topo` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id_utilsateur` INT NOT NULL,
  `nom` VARCHAR(256) NOT NULL DEFAULT 'topo_t',
  `est_publie` TINYINT NOT NULL DEFAULT 0,
  `est_disponible` TINYINT NOT NULL DEFAULT 0,
  `resume` VARCHAR(256) NULL,
  PRIMARY KEY (`id_topo`),
  CONSTRAINT `fk_topo_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilsateur`)
    REFERENCES `ocr_projet06`.`utilisateur` (`id_utilsateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_topo_utilisateur1_idx` ON `ocr_projet06`.`topo` (`utilisateur_id_utilsateur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`spot` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`spot` (
  `idspot` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id_utilsateur` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL DEFAULT 'spot_s',
  `localisation` VARCHAR(45) NOT NULL DEFAULT 'localisatiion_spot_s',
  PRIMARY KEY (`idspot`),
  CONSTRAINT `fk_spot_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilsateur`)
    REFERENCES `ocr_projet06`.`utilisateur` (`id_utilsateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_spot_utilisateur1_idx` ON `ocr_projet06`.`spot` (`utilisateur_id_utilsateur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`secteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`secteur` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`secteur` (
  `idsecteur` INT NOT NULL AUTO_INCREMENT,
  `spot_idspot` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL DEFAULT 'secteur_s',
  PRIMARY KEY (`idsecteur`),
  CONSTRAINT `fk_secteur_spot1`
    FOREIGN KEY (`spot_idspot`)
    REFERENCES `ocr_projet06`.`spot` (`idspot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_secteur_spot1_idx` ON `ocr_projet06`.`secteur` (`spot_idspot` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`voie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`voie` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`voie` (
  `idvoie` INT NOT NULL AUTO_INCREMENT,
  `secteur_idsecteur` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL DEFAULT 'voie_v',
  PRIMARY KEY (`idvoie`),
  CONSTRAINT `fk_voie_secteur1`
    FOREIGN KEY (`secteur_idsecteur`)
    REFERENCES `ocr_projet06`.`secteur` (`idsecteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_voie_secteur1_idx` ON `ocr_projet06`.`voie` (`secteur_idsecteur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`longueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`longueur` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`longueur` (
  `idlongueur` INT NOT NULL AUTO_INCREMENT,
  `voie_idvoie` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cotation` VARCHAR(45) NULL,
  `nombre_de_spits` INT NULL,
  PRIMARY KEY (`idlongueur`),
  CONSTRAINT `fk_longueur_voie1`
    FOREIGN KEY (`voie_idvoie`)
    REFERENCES `ocr_projet06`.`voie` (`idvoie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_longueur_voie1_idx` ON `ocr_projet06`.`longueur` (`voie_idvoie` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocr_projet06`.`commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocr_projet06`.`commentaire` ;

CREATE TABLE IF NOT EXISTS `ocr_projet06`.`commentaire` (
  `idcommentaire` INT NOT NULL AUTO_INCREMENT,
  `spot_idspot` INT NOT NULL,
  `texte` VARCHAR(256) NULL DEFAULT 'donnes ton avis sur c espot',
  `est_visible` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcommentaire`),
  CONSTRAINT `fk_commentaire_spot`
    FOREIGN KEY (`spot_idspot`)
    REFERENCES `ocr_projet06`.`spot` (`idspot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaire_spot_idx` ON `ocr_projet06`.`commentaire` (`spot_idspot` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`compte_utilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`compte_utilisateur` (`id_compte`, `mdp`, `login`, `droits`) VALUES (DEFAULT, 'mdp_01', 'login_01', 'U');
INSERT INTO `ocr_projet06`.`compte_utilisateur` (`id_compte`, `mdp`, `login`, `droits`) VALUES (DEFAULT, 'mdp_02', 'login_02', 'M');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`utilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`utilisateur` (`id_utilsateur`, `compte_utilisateur_id_compte`, `nom`, `email`) VALUES (DEFAULT, 1, 'user_01', 'user_01@mail.fr');
INSERT INTO `ocr_projet06`.`utilisateur` (`id_utilsateur`, `compte_utilisateur_id_compte`, `nom`, `email`) VALUES (DEFAULT, 2, 'user_02', 'user_02@mail.fr');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`topo`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`topo` (`id_topo`, `utilisateur_id_utilsateur`, `nom`, `est_publie`, `est_disponible`, `resume`) VALUES (DEFAULT, 1, 'topo_01', 1, 1, 'resume_topo_01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`spot`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`spot` (`idspot`, `utilisateur_id_utilsateur`, `nom`, `localisation`) VALUES (DEFAULT, 1, 'spot_01', 'localisation_spot01');
INSERT INTO `ocr_projet06`.`spot` (`idspot`, `utilisateur_id_utilsateur`, `nom`, `localisation`) VALUES (DEFAULT, 2, 'spot_02', 'localisation_spot02');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`secteur`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`secteur` (`idsecteur`, `spot_idspot`, `nom`) VALUES (DEFAULT, 1, 'secteur_01');
INSERT INTO `ocr_projet06`.`secteur` (`idsecteur`, `spot_idspot`, `nom`) VALUES (DEFAULT, 2, 'secteur_02');
INSERT INTO `ocr_projet06`.`secteur` (`idsecteur`, `spot_idspot`, `nom`) VALUES (DEFAULT, 1, 'secteur_03');
INSERT INTO `ocr_projet06`.`secteur` (`idsecteur`, `spot_idspot`, `nom`) VALUES (DEFAULT, 2, 'secteur_04');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`voie`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`voie` (`idvoie`, `secteur_idsecteur`, `nom`) VALUES (DEFAULT, 1, 'voie_01');
INSERT INTO `ocr_projet06`.`voie` (`idvoie`, `secteur_idsecteur`, `nom`) VALUES (DEFAULT, 2, 'voie_02');
INSERT INTO `ocr_projet06`.`voie` (`idvoie`, `secteur_idsecteur`, `nom`) VALUES (DEFAULT, 3, 'voie-03');
INSERT INTO `ocr_projet06`.`voie` (`idvoie`, `secteur_idsecteur`, `nom`) VALUES (DEFAULT, 4, 'voie_04');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`longueur`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 1, 'longeur_01', '3a', 10);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 1, 'longeur_02', '3b', 20);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 1, 'longeur_03', '3c', 30);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 2, 'longeur_04', '4a', 40);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 2, 'longeur_05', '5a', 50);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 3, 'longeur_06', '6a', 60);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 3, 'longeur_07', '7a', 70);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 3, 'longeur_08', '8a', 80);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 4, 'longeur_09', '9a', 90);
INSERT INTO `ocr_projet06`.`longueur` (`idlongueur`, `voie_idvoie`, `nom`, `cotation`, `nombre_de_spits`) VALUES (DEFAULT, 4, 'longeur_10', '9b', 100);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ocr_projet06`.`commentaire`
-- -----------------------------------------------------
START TRANSACTION;
USE `ocr_projet06`;
INSERT INTO `ocr_projet06`.`commentaire` (`idcommentaire`, `spot_idspot`, `texte`, `est_visible`) VALUES (DEFAULT, 1, 'comment_0101', 1);
INSERT INTO `ocr_projet06`.`commentaire` (`idcommentaire`, `spot_idspot`, `texte`, `est_visible`) VALUES (DEFAULT, 2, 'comment_0102', 1);
INSERT INTO `ocr_projet06`.`commentaire` (`idcommentaire`, `spot_idspot`, `texte`, `est_visible`) VALUES (DEFAULT, 1, 'comment_0201', 1);

COMMIT;

